### ISSUE TITLE
State doesn't change en some errors

### ISSUE THREAD

**Issue by frerejean** [nstrelow/ha_philips_android_tv#15]
Hello,

I get this error, and it`s not possible to get a state. I use my tv only with Chromecast and don't use the television options. In a previous version (don't know exactly which version) everything did work.

> Update for media_player.philips_tv fails
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/homeassistant/helpers/entity.py", line 220, in async_update_ha_state
    await self.async_device_update()
  File "/usr/local/lib/python3.7/site-packages/homeassistant/helpers/entity.py", line 377, in async_device_update
    await self.hass.async_add_executor_job(self.update)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.7/site-packages/homeassistant/util/__init__.py", line 224, in wrapper
    result = method(*args, **kwargs)
  File "/config/custom_components/philips_android_tv/media_player.py", line 244, in update
    self._tv.update()
  File "/config/custom_components/philips_android_tv/media_player.py", line 336, in update
    self.get_channels()
  File "/config/custom_components/philips_android_tv/media_player.py", line 379, in get_channels
    r = self._get_req('channeldb/tv/channelLists/all')
  File "/config/custom_components/philips_android_tv/media_player.py", line 302, in _get_req
    return json.loads(resp.text)
  File "/usr/local/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by nstrelow** [comment]
I cannot help you with this error log.
Will improve on the error log. I would advice you to use the cromecast integration instead, I think it can do all the things you want and more.

**Comment by frerejean** [comment]
I think I get this error because I don't have configure the TV Channels on my Philips.
When I go to the page: https://iptv:1926/6/channeldb/tv/channelLists/all I get an Internal Server Error

My solution:
Today I have delete everything with get_channels and it will work. No more errors

Feature Request:
Is it possible to add a configuration item that disable get_channels?

**Comment by nstrelow** [comment]
In my latest commit I added a way to catch the error you were having.
It also prints to the log, which method is actually failing, so you can report that and your TV model instead of having just the JSONDecodeError.

https://github.com/nstrelow/ha_philips_2016/commit/4375154dae6b1e7d87e4413e957d2d6e89de6bfe

**Comment by frerejean** [comment]
Thank you for this solution. 
I tested it and it works better for me than my own solution ;-)

**Comment by nstrelow** [comment]
@frerejean Awesome! Could you share the logs you get?
I would like to know which API is not working and what it returns.

There are two logs:
- "TV is not returning JSON. Either the authentification failed or your TV does not support calling....."
- "Response of TV: ..."

**Comment by frerejean** [comment]
I can only find the following logging:

- TV is not returning JSON. Either the authentification failed or your TV does not support calling channeldb/tv/channelLists/all.
15:43 custom_components/philips_android_tv/media_player.py (WARNING) - message first occured at 14:35 and shows up 352 times
-- Log Details (WARNING)
Fri Jun 14 2019 15:43:11 GMT+0200 (Central European Summer Time)
TV is not returning JSON. Either the authentification failed or your TV does not support calling channeldb/tv/channelLists/all.

**Comment by nstrelow** [comment]
> message first occured at 14:35 and shows up 352 times**
This is worrying, might spam the log

Yeah, the second message is logged under the info tag.
You have to adapt your config to see it.

Add

logger:
  default: info

**Comment by nstrelow** [comment]
And what's your TV model?
So that we can document which API is working and which is not

**Comment by frerejean** [comment]
it succeeded, this is the logging:

> 019-06-14 20:16:01 WARNING (SyncWorker_8) [custom_components.philips_android_tv.media_player] TV is not returning JSON. Either the authentification failed or your TV does not support calling channeldb/tv/channelLists/all.
> 2019-06-14 20:16:01 INFO (SyncWorker_8) [custom_components.philips_android_tv.media_player] Response of TV: <html>
> <head>
>    <title>Status page</title>
> </head>
> <body style="font-family: sans-serif;">
> <p style="font-size: 1.2em;font-weight: bold;margin: 1em 0px;">Internal Server Error</p>
> <p>The server encountered an unexpected condition which prevented it from fulfilling the request</p>
> <p>You can get technical details <a href="http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#sec10.5.1">here</a>.<br>
> Please continue your visit at our <a href="/">home page</a>.
> </p>
> </body>
> </html>

---------------------------------------------------------------------------------------------------
#### Result of the url: https://iptv/6/system

> {"menulanguage":"Dutch","name":"32PFK5500\/12","country":"Netherlands","serialnumber_encrypted":"0Gz--------------------7uk1XT7L6J2h36egGUUk=\n","softwareversion_encrypted":"NXB0Z--------------------IW47jpnVqlI55ggl+w=\n","model_encrypted":"qObdV7--------------------GNWzM3xT\/PyQF0wRg=\n","deviceid_encrypted":"wBl0vJo--------------------mTnWQRmw\/rX+etHbM=\n","nettvversion":"","epgsource":"one","api_version":{"Major":6,"Minor":1,"Patch":1},"featuring":{"jsonfeatures":{"editfavorites":["TVChannels","SatChannels"],"recordings":["List","Schedule","Manage"],"ambilight":["LoungeLight"],"menuitems":["Setup_Menu"],"textentry":["context_based","initial_string_available","editor_info_available"],"applications":["TV_Apps","TV_Games","TV_Settings"],"pointer":["not_available"],"inputkey":["key"],"activities":["intent"]},"systemfeatures":{"tvtype":"consumer","content":["dmr","dms_tad"],"tvsearch":"intent","pairing_type":"digest_auth_pairing","secured_transport":"true"}}}

**Comment by nstrelow** [comment]
This will probably not be fixable, since it is a problem on the API side.
Therefore I will close it.
