### ISSUE TITLE
custom updater replacement

### ISSUE THREAD

**Issue by alain57** [nstrelow/ha_philips_android_tv#20]
Hi,
one of the different custom component I used switched from custom updater to hacs because the first one is now deprecated (see partial deprecation message on https://github.com/custom-components/custom_updater )

The integration in HACS does not seems to be a big challenge 
https://custom-components.github.io/hacs/developer/integration/

wouldn't it make sense to move to HACS too ?

**Comment by nstrelow** [comment]
Yes, somebody already told me that.

I definitely plan on migrating, probably today.

**Comment by nstrelow** [comment]
Done. Will be in the default store when https://github.com/custom-components/hacs/pull/165 is merged.
