### ISSUE TITLE
Login attempt failed notification from the TV

### ISSUE THREAD

**Issue by miroslavpetrov** [nstrelow/ha_philips_android_tv#28]
Hi and thank you for developing the plugin. It doesn't work very well for me, but the Philips' mobile app doesn't work well for me either. I have 49pus7181 2016 Android TV and I am using the latest version of hass.io. My hassio instance is working behind an apache reverse proxy with https certificate and FQDN but access through the local ip 192.168.x.x is also possible. I have also two factor authentication enabled.

The problem that I am experiencing are constant notifications from home assistant with the following text
```
Login attempt failed
Login attempt or request with invalid authentication from 192.168.3.122
```

The IP is the IP of my TV and I get these notifications every few minutes only when the TV is turned on.

Do you have any idea what is happening?

**Comment by olbjan** [comment]
You likely once tried to access HA via your TV's browser. Anytime you turn on the TV it seems to try loading HA in the background but the token obviously expired. Try opening a different website on the TV and see if it goes away.
