### ISSUE TITLE
0.110 Beta  - Warning message

### ISSUE THREAD

**Issue by Gordontgopher** [nstrelow/ha_philips_android_tv#36]
In case you weren't already aware of changes being made in future releases, I get a warning in the logs: "2020-05-19 08:58:49 WARNING (MainThread) [homeassistant.components.media_player] MediaPlayerDevice is deprecated, modify PhilipsTV to extend MediaPlayerEntity"
Appreciate it's only a warning not an error, so this is more of an FYI than an issue (at the moment :) )

**Comment by alex3305** [comment]
I've opened PR #37 for this issue.

**Comment by nstrelow** [comment]
Fixed in #37
