### ISSUE TITLE
I have a error homeassistant-cli 

### ISSUE THREAD

**Issue by vampirete** [nstrelow/ha_philips_android_tv#43]
Hello

I am trying to install this integration and when I write "pip3 install -r requirements.txt" it appear this error

ERROR: homeassistant-cli 0.9.1 has requirement requests<3,>=2.22.0, but you'll have requests 2.13.0 which is incompatible.

What can I do?

Thanks

**Comment by nstrelow** [comment]
then change the requirement to 2.22.0 and hope that it's still works.

Also this is an issue in https://github.com/suborb/philips_android_tv

**Comment by vampirete** [comment]
Thanks for your answerd

I don't know nothing about commands os linux, but I have learned about install or upgrade. Now I have a new error, this is 

![image](https://user-images.githubusercontent.com/68235482/89521894-9aeb9d00-d7e0-11ea-88f0-bf42a7f21e67.png)

**Comment by nstrelow** [comment]
Can't help you there. Probably incompatibilities. Make an issue in the other repo
