### ISSUE TITLE
Not show playing media name only N/A - N/A

### ISSUE THREAD

**Issue by shirou93** [nstrelow/ha_philips_android_tv#49]
This integration not showing  playing media names?

Play/pause also not working.

**Comment by nstrelow** [comment]
Playing media names, no.
You can only open apps, not show the media name

**Comment by Julien-Decoen** [comment]
I've got the same issue after installing it. It looks like the integration can't get update tv status and then all conditional action not working as expected (like plan/pause/next_track/previous_track). 

This is the result when I'm playing media :
- First is with **androidtv** integration
- Second is with **philips_android_tv** integration
<img width="463" alt="Capture d’écran 2021-01-26 à 15 46 57" src="https://user-images.githubusercontent.com/22341879/105860361-c4e28700-5fed-11eb-8c7f-0ff4bae811cd.png">

Changing volume working like a charm and TV status too.

<img width="390" alt="Capture d’écran 2021-01-26 à 15 54 36" src="https://user-images.githubusercontent.com/22341879/105861292-d9734f00-5fee-11eb-93c0-43f61b6a13ae.png">

This is my configuration options :
```
- platform: philips_android_tv
  name: Télé 2
  host: !secret philips_tv
  mac: !secret philips_tv_mac
  username: !secret philips_tv_username
  password: !secret philips_tv_password
```

**Comment by nstrelow** [comment]
the androidtv component is more powerful in certain aspects.

the philips api can only do, what you can do with the philips remote app.

Please check out if that displays what you want, and if so, provide a screenshot or description and reopen the issue.
