### ISSUE TITLE
Do I have to pair with TV?

### ISSUE THREAD

**Issue by theRemoter** [nstrelow/ha_philips_android_tv#50]
Hi

Is it required to pair and auth with the TV or can I send REST calls to the tv, without the `auth` in the `session`-
meaning remove this line-
https://github.com/nstrelow/ha_philips_android_tv/blob/master/custom_components/philips_android_tv/media_player.py#L348

or send it with `null` data for the `pass` and `user` or it won't work?

**Comment by nstrelow** [comment]
Try it out :p

My TV needs authentication
