### ISSUE TITLE
TV (mediaplayer) works in HA but does not appear in Apple Home/Homekit

### ISSUE THREAD

**Issue by 71z0** [nstrelow/ha_philips_android_tv#55]
Any idea? All my components managed by Home Assistant automatically appear in the Apple Home app on my iPhone - but not the TV. 
Rebooted HA, rebooted iPhone ...... same. 
Ikea, Sonos, Unifi devices ... all shown - not the TV :-(

Did I miss something to activate?

**Comment by nstrelow** [comment]
No idea, never tried it.

Did you try the now official updated phlips js component?

**Comment by 71z0** [comment]
good question ..... I think so: https://www.home-assistant.io/integrations/philips_js
